// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2r72x18VuHI3MkkFVh69xVp9cM4L1DkI',
    appId: '1:619218652067:web:ff50435d5c8d1df95e2816',
    messagingSenderId: '619218652067',
    projectId: 'nascermais-a423e',
    authDomain: 'nascermais-a423e.firebaseapp.com',
    storageBucket: 'nascermais-a423e.firebasestorage.app',
    measurementId: 'G-ZKWXEYQ58R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnBtAS6Shr0u_Wg_nV5bPW4QsaCEVf67k',
    appId: '1:619218652067:android:2de2a1922be252145e2816',
    messagingSenderId: '619218652067',
    projectId: 'nascermais-a423e',
    storageBucket: 'nascermais-a423e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2r72x18VuHI3MkkFVh69xVp9cM4L1DkI',
    appId: '1:619218652067:web:fabd8cf7a4fde8d05e2816',
    messagingSenderId: '619218652067',
    projectId: 'nascermais-a423e',
    authDomain: 'nascermais-a423e.firebaseapp.com',
    storageBucket: 'nascermais-a423e.firebasestorage.app',
    measurementId: 'G-F6HYTE7PGG',
  );
}
